//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Srv
{
    [Serializable]
    public class MoveBlendingResponse : Message
    {
        public const string k_RosMessageName = "srv/MoveBlending";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public MoveBlendingResponse()
        {
            this.success = false;
        }

        public MoveBlendingResponse(bool success)
        {
            this.success = success;
        }

        public static MoveBlendingResponse Deserialize(MessageDeserializer deserializer) => new MoveBlendingResponse(deserializer);

        private MoveBlendingResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveBlendingResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
