//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Srv
{
    [Serializable]
    public class MoveBlendingRequest : Message
    {
        public const string k_RosMessageName = "srv/MoveBlending";
        public override string RosMessageName => k_RosMessageName;

        // ____________________________________________________________________________________________
        //  move_blending  
        // float64[50][6] pos              # target
        // std_msgs/Float64MultiArray[] pos1   # target1 [50][6]
        // std_msgs/Float64MultiArray[] pos2   # target2 [50][6]
        // int8[50]       segment              # LINE=0 , CIRCLE=1
        // float64[50]    radius               # Radius of segment 
        // ____________________________________________________________________________________________
        public Std.Float64MultiArrayMsg[] segment;
        // 50 x (pos1[6]:pos2[6]:type[1]:radius[1])        
        public sbyte pos_cnt;
        //  target cnt 
        public double[] vel;
        //  set velocity: [mm/sec], [deg/sec]
        public double[] acc;
        //  set acceleration: [mm/sec2], [deg/sec2]
        public double time;
        // = 0.0          # Time [sec] 
        public sbyte @ref;
        //  DR_BASE(0), DR_TOOL(1), DR_WORLD(2)
        //  <DR_WORLD is only available in M2.40 or later 
        public sbyte mode;
        // = 0            # MOVE_MODE_ABSOLUTE=0, MOVE_MODE_RELATIVE=1 
        public sbyte sync_type;
        // =0         # SYNC = 0, ASYNC = 1

        public MoveBlendingRequest()
        {
            this.segment = new Std.Float64MultiArrayMsg[0];
            this.pos_cnt = 0;
            this.vel = new double[2];
            this.acc = new double[2];
            this.time = 0.0;
            this.@ref = 0;
            this.mode = 0;
            this.sync_type = 0;
        }

        public MoveBlendingRequest(Std.Float64MultiArrayMsg[] segment, sbyte pos_cnt, double[] vel, double[] acc, double time, sbyte @ref, sbyte mode, sbyte sync_type)
        {
            this.segment = segment;
            this.pos_cnt = pos_cnt;
            this.vel = vel;
            this.acc = acc;
            this.time = time;
            this.@ref = @ref;
            this.mode = mode;
            this.sync_type = sync_type;
        }

        public static MoveBlendingRequest Deserialize(MessageDeserializer deserializer) => new MoveBlendingRequest(deserializer);

        private MoveBlendingRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.segment, Std.Float64MultiArrayMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.pos_cnt);
            deserializer.Read(out this.vel, sizeof(double), 2);
            deserializer.Read(out this.acc, sizeof(double), 2);
            deserializer.Read(out this.time);
            deserializer.Read(out this.@ref);
            deserializer.Read(out this.mode);
            deserializer.Read(out this.sync_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.segment);
            serializer.Write(this.segment);
            serializer.Write(this.pos_cnt);
            serializer.Write(this.vel);
            serializer.Write(this.acc);
            serializer.Write(this.time);
            serializer.Write(this.@ref);
            serializer.Write(this.mode);
            serializer.Write(this.sync_type);
        }

        public override string ToString()
        {
            return "MoveBlendingRequest: " +
            "\nsegment: " + System.String.Join(", ", segment.ToList()) +
            "\npos_cnt: " + pos_cnt.ToString() +
            "\nvel: " + System.String.Join(", ", vel.ToList()) +
            "\nacc: " + System.String.Join(", ", acc.ToList()) +
            "\ntime: " + time.ToString() +
            "\n@ref: " + @ref.ToString() +
            "\nmode: " + mode.ToString() +
            "\nsync_type: " + sync_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
